-- Add one product to Supabase: 75 Series Aluminum Door - 3+3 Panel
-- Run this after public.products has already been created.

insert into public.products (
    id,
    section,
    category,
    name,
    subtitle,
    description,
    base_rate,
    minimum_price,
    directions,
    glass_colors,
    frame_colors,
    accent,
    hero_image,
    detail_images,
    active,
    updated_at,
    color_options,
    color_information,
    stock_information
) values (
    'BD-760',
    'Doors',
    'Bifold Door',
    '75 Series Aluminum Door - 3+3 Panel',
    'Split-stack six-panel bifold system',
    '75 series aluminum bifold door system with three panels stacking to each side, black frame, large glass panels, and a clean full-frame opening.',
    50.0,
    0.0,
    '["Stack left", "Stack right", "Split stack"]'::jsonb,
    '["Clear", "Low-E", "Grey", "Bronze", "Frosted"]'::jsonb,
    '["Black", "White", "Charcoal", "Bronze", "Anodized"]'::jsonb,
    '#1F3D33',
    'uploads/bd-760-75-series-bifold-door-3-plus-3-panel-3x2.webp',
    '["uploads/bd-760-75-series-bifold-door-3-plus-3-panel-3x2.webp"]'::jsonb,
    true,
    NULL,
    '["Black", "White", "Charcoal", "Bronze", "Anodized"]'::jsonb,
    '',
    ''
)
on conflict (id) do update set
    section = excluded.section,
    category = excluded.category,
    name = excluded.name,
    subtitle = excluded.subtitle,
    description = excluded.description,
    base_rate = excluded.base_rate,
    minimum_price = excluded.minimum_price,
    directions = excluded.directions,
    glass_colors = excluded.glass_colors,
    frame_colors = excluded.frame_colors,
    accent = excluded.accent,
    hero_image = excluded.hero_image,
    detail_images = excluded.detail_images,
    active = excluded.active,
    updated_at = excluded.updated_at,
    color_options = excluded.color_options,
    color_information = excluded.color_information,
    stock_information = excluded.stock_information;
